// Order fields that are safe to return to clients — delivery_pin_hash is
// NEVER selected here (see GOTCHA-003 in debug.md).
export const clientSafeOrder = {
  id: true,
  studentId: true,
  riderId: true,
  shopId: true,
  checkpointId: true,
  universityId: true,
  itemDescription: true,
  productId: true,
  itemPrice: true,
  deliveryFee: true,
  discountApplied: true,
  surchargeApplied: true,
  totalAmount: true,
  deliveryDay: true,
  scheduledDate: true,
  isSpecialOrder: true,
  status: true,
  paidAt: true,
  deliveredAt: true,
  notes: true,
  cancellationReason: true,
  createdAt: true,
  updatedAt: true,
  shop: { select: { id: true, name: true, locationText: true, category: true, logoUrl: true } },
  checkpoint: { select: { id: true, name: true, description: true } },
  student: { select: { id: true, fullName: true, phone: true, studentId: true } },
  rider: { select: { id: true, fullName: true, phone: true } },
} as const;
